version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=darce_postgres
    ports:
      - '5454:5432'
    volumes:
      - darce_db:/tmp/postgres/data
volumes:
  darce_db:
    driver: local